name: transaction
description: A Transaction App

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

flutter:
  uses-material-design: true
  fonts:
    - family: NunitoSans
      fonts:
        - asset: assets/fonts/NunitoSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/NunitoSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/NunitoSans-Light.ttf
          weight: 300
        - asset: assets/fonts/NunitoSans-ExtraLight.ttf
          weight: 200
  assets:
    - assets/images/landing_page_decoration.png
    - assets/images/landing_page_logo.png